export const GET_PHONE_BY_ID = 'GET_PHONE_BY_ID';

export const GET_PHONES_PENDING = 'GET_PHONES_PENDING';
export const GET_PHONES_SUCCESS = 'GET_PHONES_SUCCESS';
export const GET_PHONES_FAILED = 'GET_PHONES_FAILED';
