export const GET_PHONES_PENDING = 'GET_PHONES_PENDING';
export const GET_PHONES_SUCCESS = 'GET_PHONES_SUCCESS';
export const GET_PHONES_FAILED = 'GET_PHONES_FAILED';

export const SET_SEARCHFIELD = 'SET_SEARCHFIELD';

